// quizbank.js — study questions, written in our own words from the same
// FCOM content the pages use. Each question belongs to a page (part id, or
// null for the system overview) so answers feed that page's progress.
//   { id, sys, part, q, c: [4 choices], a: index, why, ref }

const Q = (sys) => (id, part, q, c, a, why, ref) => ({ id: `${sys}.${id}`, sys, part, q, c, a, why, ref });

const h = Q('hydraulics');
const f = Q('fuel');
const e = Q('electrical');
const r = Q('air');

export const QUESTIONS = [
  // ── Hydraulics ──
  h('press', null, 'What is the normal hydraulic system pressure?', ['2,000 psi', '3,000 psi', '3,500 psi', '5,000 psi'], 1,
    'Normal pressure is 3,000 psi; 3,500 psi is the maximum.', 'FCOM 13.10.2'),
  h('elec2', 'emdpA', 'Which electric pump belongs to system A?', ['ELEC 1', 'ELEC 2', 'ENG 1', 'The standby pump'], 1,
    'ELEC 2 is in system A and ELEC 1 in system B — cross-wired so one electrical side never takes both pumps of one system.', 'FCOM 13.20.5'),
  h('edp2', 'edp2', "System B's engine-driven pump is driven by…", ['Engine 1', 'Engine 2', 'The APU', 'The PTU'], 1,
    'Engine 1 drives the A pump and engine 2 the B pump.', 'FCOM 13.20.5'),
  h('standpipe', 'resA', "After a leak in system A's engine-pump line, A's quantity settles at about…", ['0 %', '20 %', '50 %', '70 %'], 1,
    'The standpipe stops the loss at about 20 % and the ELEC 2 pump keeps system A pressurised.', 'FCOM 13.20.6'),
  h('stbyleak', 'resS', 'A standby system leak leaves system B quantity at about…', ['0 %', '20 %', '70 %', '100 %'], 2,
    "The standby reservoir shares B's; B falls and stabilises near 70 % and keeps working.", 'FCOM 13.20.10'),
  h('ptu', 'ptu', 'What does the PTU do?', ['Uses A pressure to pump B fluid for the LE devices and autoslats', 'Pressurises the standby system', 'Raises the landing gear', 'Powers the rudder'], 0,
    "It keeps the leading-edge devices and autoslats moving at the normal rate when B's engine pump is lost.", 'FCOM 13.20.7'),
  h('ptucond', 'ptu', 'Which of these is NOT a condition for the PTU to run automatically?', ['Airborne', 'B engine-pump pressure low', 'Flaps not up', 'Gear lever DOWN'], 3,
    "It needs airborne, B's engine-pump pressure below limits and flaps not up — the gear lever isn't part of it.", 'FCOM 13.20.7'),
  h('lgtv', 'lgtv', 'The landing-gear transfer valve lets system B raise the gear when…', ['Engine 1 RPM drops after takeoff', 'Engine 2 fails', 'System B is lost', 'The PTU fails'], 0,
    "Airborne, engine 1 RPM low, gear lever UP and a main gear not up: B's engine pump supplies the volume.", 'FCOM 13.20.7'),
  h('stbyusers', 'stby', 'Which of these does the standby hydraulic system power?', ['Ailerons', 'Elevators', 'Rudder', 'Trailing-edge flaps'], 2,
    'Standby powers the rudder, both reversers, LE devices (extend only) and the standby yaw damper.', 'FCOM 13.20.7'),
  h('stbyle', 'stby', 'On standby hydraulics the leading-edge devices can…', ['Extend only', 'Retract only', 'Extend and retract', 'Not move'], 0,
    'Standby drives the LE flaps and slats in the extend direction only.', 'FCOM 13.20.7'),
  h('stbyauto', 'stby', 'The standby pump starts by itself when A or B is lost and…', ['Flaps are extended, and airborne or above 60 kt', 'The gear is down', 'Below 10,000 ft', 'The APU is running'], 0,
    "Also needed: that system's FLT CONTROL switch ON. The main rudder PCU's force-fight monitor tripping starts it too.", 'FCOM 13.20.8'),
  h('heatx', 'heatx', 'Minimum fuel in the related main tank to run an electric hydraulic pump on the ground?', ['453 kg', '760 kg', '907 kg', '1,134 kg'], 1,
    "The pump's fluid is cooled through a heat exchanger in the main tank.", 'FCOM 13.20.6'),
  h('fcoff', 'fltctl', 'With FLT CONTROL A switched OFF, system A stops powering…', ['Ailerons, elevators and rudder', 'The landing gear', 'Thrust reverser 1', 'Nose-wheel steering'], 0,
    "OFF closes system A's flight-control shutoff valve to those surfaces.", 'FCOM 13.10.3'),
  h('rev1', 'revs', 'Thrust reverser No. 1 normally uses…', ['System A', 'System B', 'Standby only', 'The PTU'], 0,
    'No. 1 on A, No. 2 on B — and standby can drive both.', 'FCOM 13.20.5'),
  h('engoff', 'edp1', 'Setting the ENG 1 hydraulic pump switch OFF…', ['Stops the pump turning', "Blocks the pump's output with a blocking valve", 'Closes the engine fuel valve', 'Shuts down ELEC 2'], 1,
    'The pump keeps turning with the engine; OFF energises the blocking valve.', 'FCOM 13.10.1'),

  // ── Fuel ──
  f('ctrfirst', 'ctr', 'Why is center tank fuel used first?', ['The center pumps make more pressure', 'A timer opens the center valves', 'The crossfeed opens automatically', 'The main pumps stay off until the center is empty'], 0,
    'All six pumps can run; the stronger center pumps win at the check valves until the center tank is empty.', 'FCOM 12.20.1'),
  f('maincap', 'main1', 'Usable fuel in each main tank?', ['3,915 kg', '4,876 kg', '6,000 kg', '13,066 kg'], 0,
    '3,915 kg each (4,876 litres) at 0.8029 kg/l.', 'FCOM 12.20.4'),
  f('ctrcap', 'ctr', 'Usable fuel in the center tank?', ['3,915 kg', '8,630 kg', '13,066 kg', '20,896 kg'], 2,
    '13,066 kg; total usable is 20,896 kg.', 'FCOM 12.20.4'),
  f('imbal', 'xfeed', 'Maximum random lateral imbalance between the main tanks?', ['91 kg', '453 kg', '726 kg', '907 kg'], 1,
    '453 kg for taxi, takeoff, flight and landing. The IMBAL alert also triggers above 453 kg.', 'FCOM L.10'),
  f('config', 'ctr', 'CONFIG shows when the center tank holds more than ___ with both center pumps OFF.', ['363 kg', '453 kg', '726 kg', '907 kg'], 2,
    'More than 726 kg with both center switches off (engines running). It clears below 363 kg.', 'FCOM 12.10.5'),
  f('low', 'main1', 'The LOW fuel alert appears when a main tank drops below…', ['453 kg', '760 kg', '907 kg', '1,134 kg'], 2,
    'Below 907 kg; it stays until the tank is back above 1,134 kg.', 'FCOM 12.10.5'),
  f('autooff', 'pumpsC', 'A center tank pump senses low output pressure. What happens?', ['It shuts itself off after a short delay', 'The crossfeed opens', 'The main pumps stop', 'Nothing'], 0,
    'Auto-shutoff; switching it OFF resets the logic. Dry running a center pump is prohibited.', 'FCOM 12.20.2'),
  f('apu', 'apufeed', 'The APU takes its fuel from…', ['The left side of the manifold', 'The right side of the manifold', 'The center tank only', 'Main tank 2'], 0,
    'Left manifold with AC pumps running; otherwise suction from main tank 1, helped by a DC boost pump.', 'FCOM 12.20.3'),
  f('scav', 'scav', 'The scavenge jet pump moves leftover center fuel into…', ['Main tank 1', 'Main tank 2', 'Both main tanks', 'The APU line'], 0,
    'With the No. 1 FWD pump on, from about half-full main tank 1 onwards.', 'FCOM 12.20.3'),
  f('valves', 'spar1', 'What closes both the spar valve and the engine fuel valve?', ['Start lever to CUTOFF or fire switch pulled', 'Crossfeed open', 'Fuel pump switches OFF', 'BAT switch OFF'], 0,
    'Either the start lever at CUTOFF or the engine fire switch pulled closes both.', 'FCOM 12.20.3'),
  f('suction', 'pumps1', 'Both main tank 1 pumps fail. Engine 1…', ['Suction-feeds from main tank 1', 'Flames out immediately', 'Feeds from the center tank only', 'Switches to tank 2 automatically'], 0,
    'Suction feed through the bypass — but at altitude dissolved air can starve it until it has been used up.', 'FCOM 12.20.2'),
  f('maxtemp', 'main1', 'Maximum tank fuel temperature?', ['40 °C', '49 °C', '54 °C', '60 °C'], 1,
    'Max 49 °C; minimum −43 °C or 3 °C above freezing point, whichever is higher.', 'FCOM L.10'),
  f('station', 'refuel', 'Where is the single-point fueling station?', ['Right wing', 'Left wing', 'Nose gear well', 'Aft cargo hold'], 0,
    'Right wing; it is also used for ground transfer between tanks.', 'FCOM 12.20.4'),
  f('fix', 'xfeed', 'To correct a main tank imbalance you would…', ['Open crossfeed and switch off the pumps in the LOW tank', 'Switch off the pumps in the heavy tank', 'Open crossfeed only', 'Switch the center pumps off'], 0,
    'The heavy tank then feeds both engines until balanced; close crossfeed and restore the pumps after.', 'FCOM 12.20.2'),

  // ── Electrical ──
  e('parallel', null, 'Can two AC sources ever be paralleled on the 737?', ['No — never', 'Yes, in flight', 'Yes, on the ground', 'Only APU with external power'], 0,
    'No paralleling, and connecting a source to a transfer bus drops the one already there.', 'FCOM 6.20'),
  e('drive', 'idg1', 'What does the DRIVE light mean?', ['IDG low oil pressure', 'Generator overheat', 'Transfer bus off', 'Battery discharge'], 0,
    'Low oil pressure — from a fault, a high-temperature auto disconnect, or the DISCONNECT switch. Normal before engine start.', 'FCOM 6.10'),
  e('disc', 'idg1', 'After using the generator DISCONNECT switch, the IDG can be reconnected…', ['Only on the ground', 'In flight with the same switch', 'Automatically at idle', 'At the next engine start'], 0,
    'It cannot be reconnected in the air.', 'FCOM 6.10'),
  e('btb', 'btb', 'In flight one IDG fails with BUS TRANSFER in AUTO. What happens?', ['The BTBs close and the other IDG powers both transfer buses', 'That transfer bus stays dead', 'The APU starts automatically', 'The battery powers that bus'], 0,
    'The bus tie breakers let any working source pick up the dead side; load shedding may follow.', 'FCOM 6.20'),
  e('gpuapu', 'gpu', 'Can external power supply one transfer bus while the APU supplies the other?', ['No', 'Yes', 'Only in flight', 'Only with BUS TRANSFER OFF'], 0,
    'Whichever of the two was selected last powers both buses.', 'FCOM 6.20'),
  e('tr3', 'tr', 'TR3 normally receives power from…', ['Transfer bus 2, with bus 1 as backup', 'Transfer bus 1', 'The battery', 'The static inverter'], 0,
    'TR1 from bus 1, TR2 from bus 2, TR3 from bus 2 (backup bus 1 in AUTO).', 'FCOM 6.20'),
  e('trs', 'tr', 'How many TRs can carry the whole DC load?', ['Any one', 'Any two', 'All three are needed', 'TR3 alone'], 1,
    'Any two TRs can supply the total connected load.', 'FCOM 6.20'),
  e('batt60', 'bat', 'Minimum standby time with main + auxiliary batteries fully charged?', ['30 min', '45 min', '60 min', '90 min'], 2,
    '60 minutes with two batteries; 30 minutes with a single battery.', 'FCOM 6.20'),
  e('inv', 'inv', 'The static inverter supplies…', ['The AC standby bus from the battery', 'The DC standby bus', 'Transfer bus 1', 'The galley buses'], 0,
    'It turns 24 V DC into 115 V AC when normal power is lost.', 'FCOM 6.20'),
  e('stbyauto', 'stbypwr', 'With STANDBY POWER in AUTO, standby switches to the battery when…', ['Transfer bus 1 or DC bus 1 is lost', 'Any generator fails', 'The APU shuts down', 'BUS TRANSFER is OFF'], 0,
    'With the BAT switch ON, in the air or on the ground.', 'FCOM 6.20'),
  e('crosstie', 'tr', 'The DC cross bus tie opens automatically at…', ['Glide-slope capture on an ILS', 'Takeoff', 'Gear up', '10,000 ft'], 0,
    'So one failure cannot take both nav receivers and flight-control computers; it also opens with BUS TRANSFER OFF.', 'FCOM 6.20'),
  e('apushed', 'apugen', 'In flight with the APU as the only source…', ['All galley and main buses are shed', 'Nothing is shed', 'Only standby buses are powered', 'The TRs disconnect'], 0,
    'On the ground the APU tries to carry the full load and sheds only if it overloads.', 'FCOM 6.20'),
  e('volts', 'bat', 'Battery voltage range?', ['22–30 V', '24–28 V', '18–32 V', '26–30 V'], 0,
    '24 V nickel-cadmium battery, operating range 22–30 V.', 'FCOM 6.20'),
  e('apualt', 'apugen', 'APU electrical load: maximum altitude?', ['10,000 ft', '17,000 ft', '25,000 ft', '41,000 ft'], 3,
    'Electrical load to 41,000 ft; APU bleed + electrical in flight only to 10,000 ft.', 'FCOM L.10'),

  // ── Air systems ──
  r('stage', 'bleed1', 'Engine bleed air normally comes from the…', ['5th stage', '9th stage', '3rd stage', 'Fan stage'], 0,
    'The 9th stage high-stage valve opens only when the 5th stage isn\'t enough, e.g. at low power.', 'FCOM 2.20'),
  r('iso', 'iso', 'With the isolation valve in AUTO, it closes when…', ['Both engine bleeds ON and both packs AUTO or HIGH', 'The APU bleed is ON', 'One pack is OFF', 'On the ground'], 0,
    'Turn any engine bleed or pack switch OFF and it opens. APU bleed has no effect.', 'FCOM 2.20'),
  r('dual', 'apubleed', 'DUAL BLEED on means…', ['APU bleed open with an engine bleed able to connect — keep thrust at idle', 'Both packs are off', 'A bleed has tripped', 'A duct is leaking'], 0,
    'APU air could back-pressure the engine 9th-stage valve.', 'FCOM 2.20'),
  r('apualt', 'apubleed', 'APU bleed: maximum altitude?', ['10,000 ft', '15,000 ft', '17,000 ft', '25,000 ft'], 2,
    '17,000 ft for APU bleed; 10,000 ft for bleed + electrical in flight.', 'FCOM L.10'),
  r('autohigh', 'packL', 'Airborne, flaps up, both packs AUTO — one pack fails. The other pack…', ['Goes to high flow automatically', 'Trips too', 'Stays at normal flow', 'Shuts off'], 0,
    'Inhibited on the ground or with flaps out, to protect single-engine performance.', 'FCOM 2.31'),
  r('relief', 'ofv', 'Maximum cabin differential (relief valves)?', ['7.8 psi', '8.35 psi', '8.75 psi', '9.1 psi'], 3,
    'Two relief valves limit the differential to 9.1 psi.', 'FCOM L.10'),
  r('horn', null, 'The cabin altitude warning horn sounds above…', ['8,000 ft', '10,000 ft', '12,000 ft', '14,000 ft'], 1,
    'Above 10,000 ft cabin altitude; ALT HORN CUTOUT silences it.', 'FCOM 2.10'),
  r('fd', 'packL', 'Which pack supplies the flight deck directly?', ['Left pack', 'Right pack', 'Both, through the mix manifold only', 'Neither'], 0,
    'Left pack air goes to the flight deck before the mix manifold.', 'FCOM 2.31'),
  r('wbo', 'wbovht', 'WING-BODY OVERHEAT indicates…', ['A bleed air duct leak', 'A pack overheat', 'An engine fire', 'An APU fire'], 0,
    'Sensors along the strut, inboard leading edge, AC bay, keel beam and APU duct.', 'FCOM 2.10'),
  r('man', 'ofv', 'In MAN mode the outflow valve is driven by…', ['A separate DC motor on DC standby, full travel in up to 20 s', 'The auto controller', 'Hydraulic pressure', 'Cabin air pressure'], 0,
    'Faster than AUTO/ALTN — small movements make big cabin rates.', 'FCOM 2.40'),
  r('ctrl', 'cpc', 'A single pressurisation controller fails. You see…', ['AUTO FAIL + ALTN, with automatic transfer to ALTN', 'MANUAL', 'Nothing', 'OFF SCHED DESCENT'], 0,
    'AUTO FAIL alone means both controllers failed — use MAN.', 'FCOM 2.40'),
  r('diff', null, 'Cruise differential with FLT ALT between 28,000 and 37,000 ft?', ['7.45 psid', '7.80 psid', '8.35 psid', '9.1 psid'], 1,
    '7.45 at or below 28,000; 7.80 to 37,000; 8.35 above.', 'FCOM 2.40'),
  r('high', 'packL', 'With engine bleeds ON, packs in HIGH are not used for…', ['Takeoff, approach and landing', 'Cruise', 'Descent above 10,000 ft', 'Ground operation on the APU'], 0,
    'Fire and smoke checklists that call for HIGH take precedence.', 'FCOM L.10'),
  r('ram', 'ram', 'On the ground the ram air inlet doors are…', ['Fully open', 'Closed', 'Modulating', 'Open only with the APU running'], 0,
    'Fully open on the ground and in slow flight with flaps out; RAM DOOR FULL OPEN shows it.', 'FCOM 2.31'),
];

export const questionsFor = (sys, part) => QUESTIONS.filter((q) => q.sys === sys && (part === undefined || q.part === part));
