// quizbank.js — study questions, written in our own words from the same
// FCOM content the pages use. Each question belongs to a page (part id, or
// null for the system overview) so answers feed that page's progress.
//   { id, sys, part, q, c: [4 choices], a: index, why, ref }

const Q = (sys) => (id, part, q, c, a, why, ref) => ({ id: `${sys}.${id}`, sys, part, q, c, a, why, ref });

const h = Q('hydraulics');
const f = Q('fuel');
const e = Q('electrical');
const r = Q('air');
const en = Q('engines');
const fp = Q('fire');
const fc = Q('flightcontrols');
const lg = Q('gear');
const ai = Q('antiice');
const w = Q('warnings');
const af = Q('autoflight');
const ins = Q('instruments');
const nav = Q('fms');
const cm = Q('comms');
const g = Q('general');

export const QUESTIONS = [
  // ── Hydraulics ──
  h('press', null, 'What is the normal hydraulic system pressure?', ['2,000 psi', '3,000 psi', '3,500 psi', '5,000 psi'], 1,
    'Normal pressure is 3,000 psi; 3,500 psi is the maximum.', 'FCOM 13.10.2'),
  h('elec2', 'emdpA', 'Which electric pump belongs to system A?', ['ELEC 1', 'ELEC 2', 'ENG 1', 'The standby pump'], 1,
    'ELEC 2 is in system A and ELEC 1 in system B — cross-wired so one electrical side never takes both pumps of one system.', 'FCOM 13.20.5'),
  h('edp2', 'edp2', "System B's engine-driven pump is driven by…", ['Engine 1', 'Engine 2', 'The APU', 'The PTU'], 1,
    'Engine 1 drives the A pump and engine 2 the B pump.', 'FCOM 13.20.5'),
  h('standpipe', 'resA', "After a leak in system A's engine-pump line, A's quantity settles at about…", ['0 %', '20 %', '50 %', '70 %'], 1,
    'The standpipe stops the loss at about 20 % and the ELEC 2 pump keeps system A pressurised.', 'FCOM 13.20.6'),
  h('stbyleak', 'resS', 'A standby system leak leaves system B quantity at about…', ['0 %', '20 %', '70 %', '100 %'], 2,
    "The standby reservoir shares B's; B falls and stabilises near 70 % and keeps working.", 'FCOM 13.20.10'),
  h('ptu', 'ptu', 'What does the PTU do?', ['Uses A pressure to pump B fluid for the LE devices and autoslats', 'Pressurises the standby system', 'Raises the landing gear', 'Powers the rudder'], 0,
    "It keeps the leading-edge devices and autoslats moving at the normal rate when B's engine pump is lost.", 'FCOM 13.20.7'),
  h('ptucond', 'ptu', 'Which of these is NOT a condition for the PTU to run automatically?', ['Airborne', 'B engine-pump pressure low', 'Flaps not up', 'Gear lever DOWN'], 3,
    "It needs airborne, B's engine-pump pressure below limits and flaps not up — the gear lever isn't part of it.", 'FCOM 13.20.7'),
  h('lgtv', 'lgtv', 'The landing-gear transfer valve lets system B raise the gear when…', ['Engine 1 RPM drops after takeoff', 'Engine 2 fails', 'System B is lost', 'The PTU fails'], 0,
    "Airborne, engine 1 RPM low, gear lever UP and a main gear not up: B's engine pump supplies the volume.", 'FCOM 13.20.7'),
  h('stbyusers', 'stby', 'Which of these does the standby hydraulic system power?', ['Ailerons', 'Elevators', 'Rudder', 'Trailing-edge flaps'], 2,
    'Standby powers the rudder, both reversers, LE devices (extend only) and the standby yaw damper.', 'FCOM 13.20.7'),
  h('stbyle', 'stby', 'On standby hydraulics the leading-edge devices can…', ['Extend only', 'Retract only', 'Extend and retract', 'Not move'], 0,
    'Standby drives the LE flaps and slats in the extend direction only.', 'FCOM 13.20.7'),
  h('stbyauto', 'stby', 'The standby pump starts by itself when A or B is lost and…', ['Flaps are extended, and airborne or above 60 kt', 'The gear is down', 'Below 10,000 ft', 'The APU is running'], 0,
    "Also needed: that system's FLT CONTROL switch ON. The main rudder PCU's force-fight monitor tripping starts it too.", 'FCOM 13.20.8'),
  h('heatx', 'heatx', 'Minimum fuel in the related main tank to run an electric hydraulic pump on the ground?', ['453 kg', '760 kg', '907 kg', '1,134 kg'], 1,
    "The pump's fluid is cooled through a heat exchanger in the main tank.", 'FCOM 13.20.6'),
  h('fcoff', 'fltctl', 'With FLT CONTROL A switched OFF, system A stops powering…', ['Ailerons, elevators and rudder', 'The landing gear', 'Thrust reverser 1', 'Nose-wheel steering'], 0,
    "OFF closes system A's flight-control shutoff valve to those surfaces.", 'FCOM 13.10.3'),
  h('rev1', 'revs', 'Thrust reverser No. 1 normally uses…', ['System A', 'System B', 'Standby only', 'The PTU'], 0,
    'No. 1 on A, No. 2 on B — and standby can drive both.', 'FCOM 13.20.5'),
  h('engoff', 'edp1', 'Setting the ENG 1 hydraulic pump switch OFF…', ['Stops the pump turning', "Blocks the pump's output with a blocking valve", 'Closes the engine fuel valve', 'Shuts down ELEC 2'], 1,
    'The pump keeps turning with the engine; OFF energises the blocking valve.', 'FCOM 13.10.1'),

  // ── Fuel ──
  f('ctrfirst', 'ctr', 'Why is center tank fuel used first?', ['The center pumps make more pressure', 'A timer opens the center valves', 'The crossfeed opens automatically', 'The main pumps stay off until the center is empty'], 0,
    'All six pumps can run; the stronger center pumps win at the check valves until the center tank is empty.', 'FCOM 12.20.1'),
  f('maincap', 'main1', 'Usable fuel in each main tank?', ['3,915 kg', '4,876 kg', '6,000 kg', '13,066 kg'], 0,
    '3,915 kg each (4,876 litres) at 0.8029 kg/l.', 'FCOM 12.20.4'),
  f('ctrcap', 'ctr', 'Usable fuel in the center tank?', ['3,915 kg', '8,630 kg', '13,066 kg', '20,896 kg'], 2,
    '13,066 kg; total usable is 20,896 kg.', 'FCOM 12.20.4'),
  f('imbal', 'xfeed', 'Maximum random lateral imbalance between the main tanks?', ['91 kg', '453 kg', '726 kg', '907 kg'], 1,
    '453 kg for taxi, takeoff, flight and landing. The IMBAL alert also triggers above 453 kg.', 'FCOM L.10'),
  f('config', 'ctr', 'CONFIG shows when the center tank holds more than ___ with both center pumps OFF.', ['363 kg', '453 kg', '726 kg', '907 kg'], 2,
    'More than 726 kg with both center switches off (engines running). It clears below 363 kg.', 'FCOM 12.10.5'),
  f('low', 'main1', 'The LOW fuel alert appears when a main tank drops below…', ['453 kg', '760 kg', '907 kg', '1,134 kg'], 2,
    'Below 907 kg; it stays until the tank is back above 1,134 kg.', 'FCOM 12.10.5'),
  f('autooff', 'pumpsC', 'A center tank pump senses low output pressure. What happens?', ['It shuts itself off after a short delay', 'The crossfeed opens', 'The main pumps stop', 'Nothing'], 0,
    'Auto-shutoff; switching it OFF resets the logic. Dry running a center pump is prohibited.', 'FCOM 12.20.2'),
  f('apu', 'apufeed', 'The APU takes its fuel from…', ['The left side of the manifold', 'The right side of the manifold', 'The center tank only', 'Main tank 2'], 0,
    'Left manifold with AC pumps running; otherwise suction from main tank 1, helped by a DC boost pump.', 'FCOM 12.20.3'),
  f('scav', 'scav', 'The scavenge jet pump moves leftover center fuel into…', ['Main tank 1', 'Main tank 2', 'Both main tanks', 'The APU line'], 0,
    'With the No. 1 FWD pump on, from about half-full main tank 1 onwards.', 'FCOM 12.20.3'),
  f('valves', 'spar1', 'What closes both the spar valve and the engine fuel valve?', ['Start lever to CUTOFF or fire switch pulled', 'Crossfeed open', 'Fuel pump switches OFF', 'BAT switch OFF'], 0,
    'Either the start lever at CUTOFF or the engine fire switch pulled closes both.', 'FCOM 12.20.3'),
  f('suction', 'pumps1', 'Both main tank 1 pumps fail. Engine 1…', ['Suction-feeds from main tank 1', 'Flames out immediately', 'Feeds from the center tank only', 'Switches to tank 2 automatically'], 0,
    'Suction feed through the bypass — but at altitude dissolved air can starve it until it has been used up.', 'FCOM 12.20.2'),
  f('maxtemp', 'main1', 'Maximum tank fuel temperature?', ['40 °C', '49 °C', '54 °C', '60 °C'], 1,
    'Max 49 °C; minimum −43 °C or 3 °C above freezing point, whichever is higher.', 'FCOM L.10'),
  f('station', 'refuel', 'Where is the single-point fueling station?', ['Right wing', 'Left wing', 'Nose gear well', 'Aft cargo hold'], 0,
    'Right wing; it is also used for ground transfer between tanks.', 'FCOM 12.20.4'),
  f('fix', 'xfeed', 'To correct a main tank imbalance you would…', ['Open crossfeed and switch off the pumps in the LOW tank', 'Switch off the pumps in the heavy tank', 'Open crossfeed only', 'Switch the center pumps off'], 0,
    'The heavy tank then feeds both engines until balanced; close crossfeed and restore the pumps after.', 'FCOM 12.20.2'),

  // ── Electrical ──
  e('parallel', null, 'Can two AC sources ever be paralleled on the 737?', ['No — never', 'Yes, in flight', 'Yes, on the ground', 'Only APU with external power'], 0,
    'No paralleling, and connecting a source to a transfer bus drops the one already there.', 'FCOM 6.20'),
  e('drive', 'idg1', 'What does the DRIVE light mean?', ['IDG low oil pressure', 'Generator overheat', 'Transfer bus off', 'Battery discharge'], 0,
    'Low oil pressure — from a fault, a high-temperature auto disconnect, or the DISCONNECT switch. Normal before engine start.', 'FCOM 6.10'),
  e('disc', 'idg1', 'After using the generator DISCONNECT switch, the IDG can be reconnected…', ['Only on the ground', 'In flight with the same switch', 'Automatically at idle', 'At the next engine start'], 0,
    'It cannot be reconnected in the air.', 'FCOM 6.10'),
  e('btb', 'btb', 'In flight one IDG fails with BUS TRANSFER in AUTO. What happens?', ['The BTBs close and the other IDG powers both transfer buses', 'That transfer bus stays dead', 'The APU starts automatically', 'The battery powers that bus'], 0,
    'The bus tie breakers let any working source pick up the dead side; load shedding may follow.', 'FCOM 6.20'),
  e('gpuapu', 'gpu', 'Can external power supply one transfer bus while the APU supplies the other?', ['No', 'Yes', 'Only in flight', 'Only with BUS TRANSFER OFF'], 0,
    'Whichever of the two was selected last powers both buses.', 'FCOM 6.20'),
  e('tr3', 'tr', 'TR3 normally receives power from…', ['Transfer bus 2, with bus 1 as backup', 'Transfer bus 1', 'The battery', 'The static inverter'], 0,
    'TR1 from bus 1, TR2 from bus 2, TR3 from bus 2 (backup bus 1 in AUTO).', 'FCOM 6.20'),
  e('trs', 'tr', 'How many TRs can carry the whole DC load?', ['Any one', 'Any two', 'All three are needed', 'TR3 alone'], 1,
    'Any two TRs can supply the total connected load.', 'FCOM 6.20'),
  e('batt60', 'bat', 'Minimum standby time with main + auxiliary batteries fully charged?', ['30 min', '45 min', '60 min', '90 min'], 2,
    '60 minutes with two batteries; 30 minutes with a single battery.', 'FCOM 6.20'),
  e('inv', 'inv', 'The static inverter supplies…', ['The AC standby bus from the battery', 'The DC standby bus', 'Transfer bus 1', 'The galley buses'], 0,
    'It turns 24 V DC into 115 V AC when normal power is lost.', 'FCOM 6.20'),
  e('stbyauto', 'stbypwr', 'With STANDBY POWER in AUTO, standby switches to the battery when…', ['Transfer bus 1 or DC bus 1 is lost', 'Any generator fails', 'The APU shuts down', 'BUS TRANSFER is OFF'], 0,
    'With the BAT switch ON, in the air or on the ground.', 'FCOM 6.20'),
  e('crosstie', 'tr', 'The DC cross bus tie opens automatically at…', ['Glide-slope capture on an ILS', 'Takeoff', 'Gear up', '10,000 ft'], 0,
    'So one failure cannot take both nav receivers and flight-control computers; it also opens with BUS TRANSFER OFF.', 'FCOM 6.20'),
  e('apushed', 'apugen', 'In flight with the APU as the only source…', ['All galley and main buses are shed', 'Nothing is shed', 'Only standby buses are powered', 'The TRs disconnect'], 0,
    'On the ground the APU tries to carry the full load and sheds only if it overloads.', 'FCOM 6.20'),
  e('volts', 'bat', 'Battery voltage range?', ['22–30 V', '24–28 V', '18–32 V', '26–30 V'], 0,
    '24 V nickel-cadmium battery, operating range 22–30 V.', 'FCOM 6.20'),
  e('apualt', 'apugen', 'APU electrical load: maximum altitude?', ['10,000 ft', '17,000 ft', '25,000 ft', '41,000 ft'], 3,
    'Electrical load to 41,000 ft; APU bleed + electrical in flight only to 10,000 ft.', 'FCOM L.10'),

  // ── Air systems ──
  r('stage', 'bleed1', 'Engine bleed air normally comes from the…', ['5th stage', '9th stage', '3rd stage', 'Fan stage'], 0,
    'The 9th stage high-stage valve opens only when the 5th stage isn\'t enough, e.g. at low power.', 'FCOM 2.20'),
  r('iso', 'iso', 'With the isolation valve in AUTO, it closes when…', ['Both engine bleeds ON and both packs AUTO or HIGH', 'The APU bleed is ON', 'One pack is OFF', 'On the ground'], 0,
    'Turn any engine bleed or pack switch OFF and it opens. APU bleed has no effect.', 'FCOM 2.20'),
  r('dual', 'apubleed', 'DUAL BLEED on means…', ['APU bleed open with an engine bleed able to connect — keep thrust at idle', 'Both packs are off', 'A bleed has tripped', 'A duct is leaking'], 0,
    'APU air could back-pressure the engine 9th-stage valve.', 'FCOM 2.20'),
  r('apualt', 'apubleed', 'APU bleed: maximum altitude?', ['10,000 ft', '15,000 ft', '17,000 ft', '25,000 ft'], 2,
    '17,000 ft for APU bleed; 10,000 ft for bleed + electrical in flight.', 'FCOM L.10'),
  r('autohigh', 'packL', 'Airborne, flaps up, both packs AUTO — one pack fails. The other pack…', ['Goes to high flow automatically', 'Trips too', 'Stays at normal flow', 'Shuts off'], 0,
    'Inhibited on the ground or with flaps out, to protect single-engine performance.', 'FCOM 2.31'),
  r('relief', 'ofv', 'Maximum cabin differential (relief valves)?', ['7.8 psi', '8.35 psi', '8.75 psi', '9.1 psi'], 3,
    'Two relief valves limit the differential to 9.1 psi.', 'FCOM L.10'),
  r('horn', null, 'The cabin altitude warning horn sounds above…', ['8,000 ft', '10,000 ft', '12,000 ft', '14,000 ft'], 1,
    'Above 10,000 ft cabin altitude; ALT HORN CUTOUT silences it.', 'FCOM 2.10'),
  r('fd', 'packL', 'Which pack supplies the flight deck directly?', ['Left pack', 'Right pack', 'Both, through the mix manifold only', 'Neither'], 0,
    'Left pack air goes to the flight deck before the mix manifold.', 'FCOM 2.31'),
  r('wbo', 'wbovht', 'WING-BODY OVERHEAT indicates…', ['A bleed air duct leak', 'A pack overheat', 'An engine fire', 'An APU fire'], 0,
    'Sensors along the strut, inboard leading edge, AC bay, keel beam and APU duct.', 'FCOM 2.10'),
  r('man', 'ofv', 'In MAN mode the outflow valve is driven by…', ['A separate DC motor on DC standby, full travel in up to 20 s', 'The auto controller', 'Hydraulic pressure', 'Cabin air pressure'], 0,
    'Faster than AUTO/ALTN — small movements make big cabin rates.', 'FCOM 2.40'),
  r('ctrl', 'cpc', 'A single pressurisation controller fails. You see…', ['AUTO FAIL + ALTN, with automatic transfer to ALTN', 'MANUAL', 'Nothing', 'OFF SCHED DESCENT'], 0,
    'AUTO FAIL alone means both controllers failed — use MAN.', 'FCOM 2.40'),
  r('diff', null, 'Cruise differential with FLT ALT between 28,000 and 37,000 ft?', ['7.45 psid', '7.80 psid', '8.35 psid', '9.1 psid'], 1,
    '7.45 at or below 28,000; 7.80 to 37,000; 8.35 above.', 'FCOM 2.40'),
  r('high', 'packL', 'With engine bleeds ON, packs in HIGH are not used for…', ['Takeoff, approach and landing', 'Cruise', 'Descent above 10,000 ft', 'Ground operation on the APU'], 0,
    'Fire and smoke checklists that call for HIGH take precedence.', 'FCOM L.10'),
  r('ram', 'ram', 'On the ground the ram air inlet doors are…', ['Fully open', 'Closed', 'Modulating', 'Open only with the APU running'], 0,
    'Fully open on the ground and in slow flight with flaps out; RAM DOOR FULL OPEN shows it.', 'FCOM 2.31'),
  // ── Engines, APU ──
  en('lever', 'start', 'During a ground start, the start lever goes to IDLE at about…', ['15 % N2', '25 % N2 (or max motoring)', '40 % N2', '56 % N2'], 1,
    'IDLE at about 25 % N2 or maximum motoring, whichever comes first.', 'FCOM 7.20'),
  en('cutout', 'start', 'The starter cuts out (ENGINE START back to AUTO) at about…', ['25 % N2', '46 % N2', '56 % N2', '70 % N2'], 2,
    'The start valve closes and the switch returns at about 56 % N2.', 'FCOM 7.20'),
  en('ign', 'ign', 'Engine ignition must be on for…', ['Taxi only', 'Takeoff, landing, heavy rain and anti-ice operation', 'Cruise above FL250', 'Never — AUTO handles it'], 1,
    'A limitation: takeoff, landing, heavy rain and anti-ice operation.', 'FCOM L.10'),
  en('rev', 'rev', 'Reverse thrust may be used…', ['In flight below 10,000 ft', 'On the ground only', 'Any time below 200 kt', 'Only with autobrake'], 1,
    'Reverse thrust is for ground use only.', 'FCOM L.10'),
  en('apubleed', 'apu', 'Before using the APU as a bleed air source it should run for…', ['30 s', '1 min', '2 min', '5 min'], 2,
    'Two minutes of running before it is used as a bleed source.', 'FCOM L.10'),
  // ── Fire protection ──
  fp('pull', 'fsw', 'Pulling an engine fire switch does NOT…', ['Close the spar fuel valve', 'Close the engine bleed valve', 'Fire a bottle', 'Trip the generator'], 2,
    'Pulling shuts things off; rotating the switch discharges a bottle.', 'FCOM 8.20'),
  fp('bottles', 'bottles', 'How many engine fire bottles are there, and where can they go?', ['One per engine, own engine only', 'Two, either can go to either engine', 'Three, one shared', 'Two, both to the same engine together'], 1,
    'Two bottles; rotating left or right fires one into the selected engine.', 'FCOM 8.20'),
  fp('cargo', 'cargo', 'Total cargo fire suppression time is about…', ['60 min', '120 min', '195 min', '6 hours'], 2,
    'Initial discharge plus metered flow gives about 195 minutes.', 'FCOM 8.20'),
  fp('loops', 'loops1', 'With OVHT DET in NORMAL, a fire warning needs…', ['Either loop', 'Both loops', 'Loop A only', 'The test switch'], 1,
    'Both loops must detect; select A or B alone if one loop is faulty.', 'FCOM 8.20'),
  // ── Flight controls ──
  fc('flapalt', 'flaps', 'Maximum altitude with flaps extended is…', ['10,000 ft', '15,000 ft', '20,000 ft', '25,000 ft'], 2,
    'A limitation: 20,000 ft with flaps extended.', 'FCOM L.10'),
  fc('sb', 'sb', 'In flight the speedbrake lever must not go beyond…', ['ARMED', 'FLIGHT DETENT', 'UP', 'DOWN'], 1,
    'Not beyond the FLIGHT DETENT in flight, and no speedbrakes below 1,000 ft RA.', 'FCOM L.10'),
  fc('mach', 'elev', 'Mach trim works above about…', ['Mach .50', 'Mach .615', 'Mach .74', 'Mach .82'], 1,
    'Mach trim is active above Mach .615.', 'FCOM 9.20'),
  fc('rud', 'rud', 'Above about 137 kt the rudder load limiter…', ['Locks the rudder', 'Reduces rudder authority', 'Turns off the yaw damper', 'Switches to the standby PCU'], 1,
    'Reduced authority above 137 kt; full authority again below 132 kt.', 'FCOM 9.20'),
  fc('altflap', 'flaps', 'With ALTERNATE FLAPS the LE devices…', ['Retract and extend normally', 'Extend only, on the standby system', 'Stay where they are', 'Run on system A'], 1,
    'TE flaps run electrically; LE devices extend on standby hydraulics and cannot be retracted that way.', 'FCOM 9.20'),
  // ── Landing gear ──
  lg('rto', 'autobrake', 'RTO autobrake gives maximum braking if the takeoff is rejected above…', ['60 kt', '80 kt', '88 kt wheel speed', 'V1'], 2,
    'Above 88 kt wheel speed, when the thrust levers come to idle.', 'FCOM 14.20'),
  lg('tiller', 'nlg', 'The tiller steers the nose wheels up to…', ['7°', '40°', '78°', '90°'], 2,
    'Tiller up to 78°, rudder pedals up to 7°.', 'FCOM 14.20'),
  lg('xfr', 'lever', 'If engine 1 fails, the gear can still be raised normally thanks to…', ['The PTU', 'The transfer valve (system B)', 'The standby system', 'Manual extension'], 1,
    'The transfer valve lets system B supply the volume to retract the gear.', 'FCOM 14.20'),
  lg('green', 'lever', 'The gear is down and locked when…', ['All three red lights are out', 'At least one green light per gear is on (centre or overhead)', 'The lever is DN', 'The horn stops'], 1,
    'One green per gear, on either the centre or overhead set, is enough.', 'FCOM 14.20'),
  lg('brakes', 'brakes', 'Normal brakes are powered by…', ['System A', 'System B', 'Standby system', 'The accumulator only'], 1,
    'Normal brakes on B, alternate on A, with the accumulator as backup.', 'FCOM 14.20'),
  lg('manual', 'manual', 'With the manual extension access door open…', ['The gear retracts faster', 'Retraction is disabled', 'Autobrake disarms', 'Steering moves to system B'], 1,
    'Open door: manual extension possible in any lever position and retraction disabled.', 'FCOM 14.20'),
  // ── Anti-ice ──
  ai('icing', null, 'Icing conditions exist when OAT / TAT is at or below… with visible moisture', ['0 °C', '5 °C', '10 °C', '15 °C'], 2,
    'At or below 10 °C OAT on the ground or TAT in flight, with visible moisture or contaminated surfaces.', 'FCOM SP.16'),
  ai('wing', 'wingai', 'Wing anti-ice protects…', ['All LE slats and flaps', 'The three inboard slats on each wing', 'The Krueger flaps only', 'The wingtips'], 1,
    'Only the three inboard slats per wing — not the LE flaps or outboard slats.', 'FCOM 3.20'),
  ai('trip', 'wingai', 'On the ground with WING ANTI-ICE ON, at lift-off the switch…', ['Stays ON', 'Trips OFF', 'Goes to AUTO', 'Opens the cowl valves'], 1,
    'It trips OFF automatically when the air/ground sensing goes to air.', 'FCOM 3.20'),
  ai('probes', 'probes', 'Which of these is NOT heated?', ['Pitot probes', 'Alpha vanes', 'TAT probe', 'Static ports'], 3,
    'Pitots, alpha vanes and the TAT probe are heated; the static ports are not.', 'FCOM 3.20'),
  ai('cowlbright', 'cowl', 'COWL VALVE OPEN bright blue (not dim) means…', ['Valve open normally', 'Valve in transit or disagreeing with the switch', 'Duct overpressure', 'Engine anti-ice off'], 1,
    'Dim = open as selected; bright = in transit or disagreement.', 'FCOM 3.10'),
  // ── Warning systems ──
  w('horn', 'config', 'An intermittent horn in the climb is most likely…', ['Takeoff configuration', 'Cabin altitude', 'Landing gear', 'Overspeed'], 1,
    'Takeoff config and cabin altitude share the intermittent horn — airborne, it is the cabin.', 'FCOM 15.20'),
  w('cabalt', 'config', 'The cabin altitude warning comes on above…', ['8,000 ft', '10,000 ft', '12,000 ft', '14,000 ft'], 1,
    'Cabin altitude above 10,000 ft: intermittent horn and red CABIN ALTITUDE.', 'FCOM 15.20'),
  w('toflaps', 'config', 'The takeoff configuration warning sounds if the flaps are…', ['Between 1 and 25', 'Outside 1 to 25', 'At 5 exactly', 'Moving'], 1,
    'Flaps outside the 1–25 takeoff range (among other conditions).', 'FCOM 15.20'),
  w('clacker', 'stall', 'The overspeed clacker stops when…', ['You push MASTER CAUTION', 'Speed drops below Vmo/Mmo', 'The A/P disengages', 'After 10 s'], 1,
    'It can only be silenced by slowing below Vmo/Mmo.', 'FCOM 15.20'),
  w('gearhorn', 'config', 'With flaps above 25 and a gear not down, the gear horn…', ['Can be silenced with the cutout', 'Cannot be silenced', 'Only sounds below 200 ft', 'Needs a thrust lever at idle'], 1,
    'Flaps above 25: regardless of thrust, no cutout.', 'FCOM 15.20'),
  w('tcas', 'tcas', 'TCAS resolution advisories are inhibited below about…', ['500 ft RA', '1,000 ft RA', '1,500 ft RA', '2,500 ft RA'], 1,
    'All RAs are inhibited below about 1,000 ft RA (TA ONLY then shows).', 'FCOM 15.20'),
  // ── Automatic flight ──
  af('400', 'servos', 'After takeoff the autopilot must not be engaged below…', ['50 ft AGL', '400 ft AGL', '1,000 ft AGL', '1,500 ft AGL'], 1,
    'A limitation: not below 400 ft AGL after takeoff.', 'FCOM L.10'),
  af('single', 'approach', 'On a single-channel approach the autopilot must not remain engaged below…', ['200 ft AGL', '100 ft AGL', '50 ft AGL', 'Touchdown'], 2,
    'Single channel: not below 50 ft AGL.', 'FCOM L.10'),
  af('800', 'approach', 'For a dual-channel approach the second autopilot must be in CMD by…', ['1,500 ft RA', '800 ft RA', '500 ft RA', '200 ft RA'], 1,
    'Engage the second A/P by 800 ft RA.', 'FCOM 4.20'),
  af('retard', 'at', 'On an autoland, RETARD starts at about…', ['50 ft RA', '27 ft RA', '10 ft RA', 'Touchdown'], 1,
    'The A/T retards from about 27 ft to reach idle at touchdown; it disconnects ~2 s after touchdown.', 'FCOM 4.20'),
  af('hyd', 'servos', 'Autopilot B moves the controls through…', ['Hydraulic system A', 'Hydraulic system B', 'Both systems', 'The standby system'], 1,
    'A/P A uses system A, A/P B system B.', 'FCOM 4.20'),
  af('autoland', 'approach', 'Autoland may be used with…', ['Any flap setting', 'Flaps 15 or 30', 'Flaps 30 or 40, both engines operating', 'Flaps 40 only'], 2,
    'Flaps 30 or 40 and both engines operating.', 'FCOM L.10'),
  // ── Flight instruments ──
  ins('outbd', 'dus', 'If the captain\'s outboard DU fails…', ['Both captain DUs blank', 'The PFD moves to the inboard DU', 'The PFD moves to the upper DU', 'Use the ISFD only'], 1,
    'Automatic switching puts the PFD on the inboard DU.', 'FCOM 10.21'),
  ins('deu', 'deu', 'If one DEU fails…', ['Its three DUs blank', 'The other DEU drives all six, DSPLY SOURCE shows', 'The ISFD takes over', 'Displays freeze'], 1,
    'The remaining DEU supplies all six; a DSPLY SOURCE annunciation appears.', 'FCOM 10.21'),
  ins('aux', 'standby', 'The standby airspeed and altitude come from…', ['The captain\'s pitot', 'The auxiliary pitot and alternate static ports', 'The left ADIRU', 'GPS'], 1,
    'Auxiliary pitot and alternate static, direct to the ISFD / standby instruments.', 'FCOM 10.21'),
  ins('rvsm', null, 'For RVSM, the maximum in-flight captain vs first officer altitude difference is…', ['100 ft', '200 ft', '300 ft', '500 ft'], 1,
    'A limitation: 200 ft in flight.', 'FCOM L.10'),
  ins('aoa', 'pitot', 'AOA DISAGREE shows when the vanes differ by more than…', ['5° for 5 s', '10° for 10 s', '15° for 3 s', '20° immediately'], 1,
    'More than 10° for more than 10 s, above 400 ft RA.', 'FCOM 10.11'),
  // ── FMS / navigation ──
  nav('align', 'irs', 'IRS alignment takes…', ['About 30 s', '5 to 17 min depending on latitude', 'Exactly 10 min', '20 to 30 min'], 1,
    'Five to seventeen minutes depending on latitude.', 'FCOM 11.20'),
  nav('flash', 'irs', 'A flashing ALIGN light means…', ['Alignment complete', 'Check / re-enter the present position', 'IRS on DC power', 'IRS fault'], 1,
    'The entered position failed a comparison test or none was entered.', 'FCOM 11.20'),
  nav('ondc', 'irs', 'ON DC on the IRS panel means…', ['DC power has failed', 'The IRS is running on battery power', 'Alignment is complete', 'The IRS is in ATT'], 1,
    'AC power isn\'t normal; it runs from the switched hot battery bus (nose wheel well horn on the ground).', 'FCOM 11.20'),
  nav('att', 'irs', 'In ATT mode, heading becomes available after…', ['30 s of level flight', 'You enter the magnetic heading', 'GPS update', 'Never'], 1,
    'Attitude after ~30 s level flight; heading only once you enter it — and it drifts up to 15°/h.', 'FCOM 11.20'),
  nav('pos', 'fmc', 'The FMC\'s primary position update is…', ['DME/DME', 'VOR/DME', 'GPS', 'IRS'], 2,
    'GPS first; radio too when available; IRS alone if both are lost.', 'FCOM 11.20'),
  // ── Communications ──
  cm('alt', 'acp', 'With the ACP in ALT (degraded) mode you get…', ['All radios but no speaker', 'One fixed radio, headset only', 'Interphone only', 'Normal operation'], 1,
    'One radio through the headset; no speaker, interphones, PA or aural warnings on that side.', 'FCOM 5.20'),
  cm('aurals', 'acp', 'GPWS, TCAS and windshear aurals…', ['Follow the speaker volume', 'Come through at a fixed volume you can\'t turn off', 'Only play in the headset', 'Can be muted with the ACP'], 1,
    'Preset volume on speakers and headsets; the crew cannot control them.', 'FCOM 5.20'),
  cm('cvr', 'cvr', 'In AUTO, the voice recorder runs from first engine start until…', ['Last engine shutdown', '5 minutes after the last engine shutdown', 'The parking brake is set', 'Battery OFF'], 1,
    'Until 5 minutes after the last engine shutdown.', 'FCOM 5.10'),
  cm('pa', 'interphone', 'Which has the highest PA priority?', ['Pre-recorded announcements', 'Cabin crew handset', 'Flight deck (ACP PA or hand mic)', 'Boarding music'], 2,
    'The flight deck pre-empts everything, then cabin crew handsets, then PRAM.', 'FCOM 5.20'),
  // ── Airplane general ──
  g('oxy', 'oxygen', 'The passenger oxygen masks drop automatically at a cabin altitude of…', ['10,000 ft', '12,000 ft', '14,000 ft', '18,000 ft'], 2,
    'At 14,000 ft cabin altitude, or with PASS OXY ON.', 'FCOM 1.40'),
  g('oxyt', 'oxygen', 'Once started, passenger chemical oxygen flows for about…', ['5 min', '12 min (some ~22 min)', '45 min', 'Until switched off'], 1,
    'About 12 minutes (22 on some installations) and it cannot be stopped.', 'FCOM 1.40'),
  g('exit', 'emergency', 'With EMER EXIT LIGHTS ARMED the lights come on automatically when…', ['A door opens', 'DC bus 1 fails or AC power is lost', 'The engines stop', 'Cabin altitude exceeds 10,000 ft'], 1,
    'ARMED: on by themselves if DC bus 1 or AC power is lost.', 'FCOM 1.30'),
  g('belts', 'signs', 'FASTEN BELTS in AUTO are on when…', ['Below 10,000 ft', 'Flaps or gear are extended', 'Engines are running', 'The A/P is off'], 1,
    'On with flaps or gear extended; off when both are retracted.', 'FCOM 1.40'),
  g('wind', 'doors', 'Entry and service doors must not be operated in steady winds above…', ['25 kt', '40 kt', '50 kt', '65 kt'], 1,
    'Not in steady winds over 40 kt, and not left open in gusts over 65 kt.', 'FCOM 1.40'),
  g('lock', 'doors', 'The overwing exit flight locks engage when three doors are closed, an engine is running and…', ['The parking brake is released', 'Airborne or both thrust levers advanced', 'Flaps are up', 'The seat belt sign is on'], 1,
    'Air mode or both thrust levers advanced; they unlock otherwise or with DC lost.', 'FCOM 1.40'),
];

export const questionsFor = (sys, part) => QUESTIONS.filter((q) => q.sys === sys && (part === undefined || q.part === part));
